"""
Cross-Projection Padding Module for PS1 Sliding Window Pipeline

This module handles the complex task of applying padding across projection boundaries.
It uses metadata generated by `pancakes_v2.py` (via CSV) to identify required padding skycells,
optimized by loading each skycell only once even if needed by multiple rows (current/next).

Key features:
-   Ordered placement composition (`PaddingPlacement`) that loads each source
    skycell only once even if needed by multiple rows (current/next).
-   Localized WCS creation (`create_padding_wcs`) for accurate reprojection.
-   Edge artifact suppression (`exclude_edge_pixels`).
"""

import logging
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from astropy.wcs import WCS
from reproject import reproject_interp

from syndiff_pipeline.template_creation.processing.band_utils import process_skycell_bands, remove_background
from syndiff_pipeline.template_creation.processing.csv_utils import load_csv_data
from syndiff_pipeline.template_creation.processing.cross_projection_geometry import (
    cell_wcs_from_row,
    cd_matrix_from_row,
    padding_patch_geometry,
    valid_reprojection_footprint,
    projection_identity,
    skycell_projection_identity,
)
from syndiff_pipeline.template_creation.processing.zarr_utils import load_skycell_bands_masks_and_headers

logger = logging.getLogger(__name__)

# Constants (Must match process_ps1.py)
PAD_SIZE = 480
CELL_OVERLAP = 480
EDGE_EXCLUSION = 10


@dataclass
class SkycellPaddingInfo:
    """Information about a single padding requirement for a specific skycell."""

    skycell_name: str
    projection: str
    locations: List[str]  # e.g., ["top", "top_left"]
    cell_position: str  # "first", "last", "interior"
    row_position: str  # "top", "bottom", "middle"
    actual_index: int  # Index in the row


@dataclass(frozen=True)
class PaddingPlacement:
    """One ordered source-to-recipient replacement operation.

    Priority is part of the producer's scientific ownership contract.  A
    valid later placement replaces an earlier one at multiply covered pixels;
    it must therefore never be inferred from worker completion order.
    """

    source_skycell: str
    source_projection: str
    recipient_skycell: str
    recipient_index: int
    location: str
    priority: int


# --- Helper Functions (Ported from Notebook & modern_padding) ---


def determine_row_position(row_id: int, all_row_ids: List[int]) -> str:
    """Determine if row is top, bottom, or middle row in projection."""
    if row_id == min(all_row_ids):
        return "bottom"
    elif row_id == max(all_row_ids):
        return "top"
    else:
        return "middle"


def analyze_cell_positions(row_cells: List[str]) -> Dict[str, str]:
    """Analyze position of each cell within its actual row."""
    positions = {}
    actual_row_size = len(row_cells)

    for i, cell_name in enumerate(row_cells):
        if i == 0:
            position_type = "first"
        elif i == actual_row_size - 1:
            position_type = "last"
        else:
            position_type = "interior"
        positions[cell_name] = position_type
    return positions


def _get_cd_matrix(row: pd.Series) -> List[List[float]]:
    """Helper to extract CD matrix from row, handling CD vs CDELT/PC."""
    return cd_matrix_from_row(row)


def create_cell_wcs(cell_name: str, metadata: dict) -> WCS:
    """Create WCS object for a specific cell from metadata."""
    proj_df = metadata["dataframe"]
    cell_row = proj_df[proj_df["NAME"] == cell_name]

    if cell_row.empty:
        raise ValueError(f"Cell {cell_name} not found in metadata")

    cell_data = cell_row.iloc[0]

    return cell_wcs_from_row(cell_data)


def create_padding_wcs(master_wcs: WCS, config, location: str, cell_index: int) -> Tuple[WCS, Tuple[int, int], Tuple[float, float]]:
    """
    Create a localized WCS centered at the padding region for reprojection.
    Ported from notebook code for better accuracy than global master WCS.
    """
    cell_x_start = PAD_SIZE + cell_index * (config.cell_width - CELL_OVERLAP)
    geometry = padding_patch_geometry(
        master_wcs,
        recipient_x0=cell_x_start,
        recipient_y0=PAD_SIZE,
        cell_width=config.cell_width,
        cell_height=config.cell_height,
        location=location,
        pad_size=PAD_SIZE,
        edge_exclusion=EDGE_EXCLUSION,
    )
    y_center, x_center = geometry.center
    return geometry.wcs, geometry.shape, (y_center, x_center)


def exclude_edge_pixels(data: np.ndarray, edge_width: int = 10) -> np.ndarray:
    """Replace edge pixels with NaN to avoid edge artifacts during reprojection."""
    cleaned = data.copy()
    cleaned[:edge_width, :] = np.nan
    cleaned[-edge_width:, :] = np.nan
    cleaned[:, :edge_width] = np.nan
    cleaned[:, -edge_width:] = np.nan
    return cleaned


def determine_cell_position_from_skycell(main_skycell: str, metadata: dict) -> Tuple[int, int]:
    """Find the (row_index, cell_index) for a given skycell name in the metadata."""
    # Note: row_index here is just the index in the sorted list of rows, not the row_id
    sorted_row_ids = sorted(metadata["rows"].keys())

    for r_idx, row_id in enumerate(sorted_row_ids):
        cells = metadata["rows"][row_id]
        for c_idx, (cell_name, _) in enumerate(cells):
            if cell_name == main_skycell:
                return r_idx, c_idx
    return -1, -1


def get_cell_index_in_row(row_id: int, cell_name: str, metadata: dict) -> int:
    """Get the 0-based index of a cell within a specific row."""
    if row_id not in metadata["rows"]:
        return -1
    cells = metadata["rows"][row_id]
    for i, (name, _) in enumerate(cells):
        if name == cell_name:
            return i
    return -1


def create_master_array_wcs(metadata: dict, config, current_row_id: int) -> WCS:
    """Create WCS object for the master array based on first cell + padding offset."""
    # Get first cell's WCS information from the dataframe
    # Note: metadata["dataframe"] already contains only rows for the correct projection
    proj_df = metadata["dataframe"]
    proj_df = proj_df[proj_df["y"] == current_row_id]

    if proj_df.empty:
        raise ValueError(f"No data found for projection {metadata['projection']} and row {current_row_id}")

    proj_df = proj_df.sort_values(by=["x"])
    first_cell = proj_df.iloc[0]

    # Extract WCS parameters
    crval1 = float(first_cell.get("CRVAL1", 0.0))
    crval2 = float(first_cell.get("CRVAL2", 0.0))
    crpix1 = float(first_cell.get("CRPIX1", 0.0))
    crpix2 = float(first_cell.get("CRPIX2", 0.0))

    cd = _get_cd_matrix(first_cell)

    # Create WCS object
    master_wcs = WCS(naxis=2)
    master_wcs.wcs.crval = [crval1, crval2]
    master_wcs.wcs.crpix = [crpix1 + PAD_SIZE, crpix2 + PAD_SIZE]  # Adjust for padding
    master_wcs.wcs.cd = cd
    master_wcs.wcs.ctype = ["RA---TAN", "DEC--TAN"]
    master_wcs.wcs.cunit = ["deg", "deg"]

    return master_wcs


# --- Core Logic ---


def _parse_row_padding_requirements_df(metadata: dict, df: pd.DataFrame, row_id: int, all_row_ids: List[int]) -> Dict[str, "SkycellPaddingInfo"]:
    """
    Core implementation of parse_row_padding_requirements using a pre-loaded DataFrame.
    Avoids repeated disk I/O when called in bulk (e.g., from identify_all_padding_sources).
    """
    current_projection = metadata["projection"]

    if row_id not in metadata["rows"]:
        return {}

    row_cells = [c[0] for c in metadata["rows"][row_id]]
    row_position = determine_row_position(row_id, all_row_ids)
    cell_positions = analyze_cell_positions(row_cells)

    proj_df = df[df["projection"].astype(str) == str(current_projection)]
    row_df = proj_df[proj_df["y"] == row_id]

    requirements: Dict[str, SkycellPaddingInfo] = {}
    padding_cols = [
        "pad_skycell_top", "pad_skycell_bottom", "pad_skycell_left", "pad_skycell_right",
        "pad_skycell_top_left", "pad_skycell_top_right", "pad_skycell_bottom_left", "pad_skycell_bottom_right",
    ]

    for _, row_data in row_df.iterrows():
        main_cell_name = row_data["NAME"]
        if main_cell_name not in row_cells:
            continue

        cell_info_type = cell_positions.get(main_cell_name, "interior")

        for col in padding_cols:
            val = row_data.get(col)
            if pd.isna(val) or not str(val).strip():
                continue

            padding_cells = [c.strip() for c in str(val).split("/") if c.strip()]
            location = col.replace("pad_skycell_", "")

            for p_cell in padding_cells:
                try:
                    p_proj = p_cell.split(".")[1]
                except IndexError:
                    continue

                if p_proj == str(current_projection):
                    continue

                valid = True
                if "top" in location and row_position != "top":
                    valid = False
                if "bottom" in location and row_position != "bottom":
                    valid = False
                if "left" in location and cell_info_type != "first":
                    valid = False
                if "right" in location and cell_info_type != "last":
                    valid = False

                if not valid:
                    logger.debug(f"Skipping {location} padding {p_cell} for {main_cell_name} (filtered)")
                    continue

                if p_cell not in requirements:
                    requirements[p_cell] = SkycellPaddingInfo(
                        skycell_name=p_cell, projection=p_proj, locations=[],
                        cell_position=cell_info_type, row_position=row_position,
                        actual_index=row_cells.index(main_cell_name),
                    )
                requirements[p_cell].locations.append(location)

    return requirements


def ordered_cross_projection_placements(
    metadata: dict, df: pd.DataFrame, row_id: int, all_row_ids: List[int]
) -> list[PaddingPlacement]:
    """Normalize one row's active cross-projection operations in stable order.

    Unlike the legacy source-keyed requirements map, this keeps the recipient
    association.  One source can legitimately pad multiple recipient cells;
    merging it under a single source key loses that information.  Locations
    use the historic producer order and sources retain slash order from the
    mapping table.  Duplicate ``(source, recipient, location)`` entries keep
    their first occurrence.
    """
    if row_id not in metadata["rows"]:
        return []
    current_projection = projection_identity(metadata["projection"])
    row_cells = sorted(metadata["rows"][row_id], key=lambda item: int(item[1]))
    names = [str(item[0]) for item in row_cells]
    row_position = determine_row_position(row_id, all_row_ids)
    cell_positions = analyze_cell_positions(names)
    row_df = df[
        (df["projection"].map(projection_identity) == current_projection)
        & (df["y"] == row_id)
    ].sort_values("x")
    columns = (
        "pad_skycell_top", "pad_skycell_bottom", "pad_skycell_left", "pad_skycell_right",
        "pad_skycell_top_left", "pad_skycell_top_right", "pad_skycell_bottom_left",
        "pad_skycell_bottom_right",
    )
    placements: list[PaddingPlacement] = []
    seen: set[tuple[str, str, str]] = set()
    for _, row_data in row_df.iterrows():
        recipient = str(row_data["NAME"])
        if recipient not in cell_positions:
            continue
        cell_position = cell_positions[recipient]
        for column in columns:
            value = row_data.get(column)
            if pd.isna(value) or not str(value).strip():
                continue
            location = column.replace("pad_skycell_", "")
            if "top" in location and row_position != "top":
                continue
            if "bottom" in location and row_position != "bottom":
                continue
            if "left" in location and cell_position != "first":
                continue
            if "right" in location and cell_position != "last":
                continue
            for source in (item.strip() for item in str(value).split("/")):
                source_projection = skycell_projection_identity(source)
                if not source_projection or source_projection == current_projection:
                    continue
                key = (source, recipient, location)
                if key in seen:
                    continue
                seen.add(key)
                placements.append(PaddingPlacement(
                    source_skycell=source,
                    source_projection=source_projection,
                    recipient_skycell=recipient,
                    recipient_index=names.index(recipient),
                    location=location,
                    priority=len(placements),
                ))
    return placements


def compose_ordered_reprojected_patches(
    operations: list[tuple[int, np.ndarray, tuple[int, int, int, int], np.ndarray, np.ndarray]],
) -> None:
    """Apply prepared producer patches in explicit priority order.

    Each item is ``(priority, target, (y0,y1,x0,x1), reprojected,
    footprint)``.  Replacement (not addition) exactly matches the live
    padding contract while removing timing dependence from concurrent patch
    generation.
    """
    for _priority, target, (y0, y1, x0, x1), reprojected, footprint in sorted(
        operations, key=lambda item: item[0]
    ):
        valid = valid_reprojection_footprint(reprojected, footprint)
        if np.any(valid):
            destination = target[y0:y1, x0:x1]
            destination[valid] = reprojected[valid]


def _load_padding_source_once(
    placement: PaddingPlacement,
    *,
    band_cache: dict | None,
    ingest_config: dict,
    remove_saturated_stars: bool,
    current_df: pd.DataFrame,
    gaia_catalog: pd.DataFrame | None = None,
    bright_star_mag_threshold: float = 13.0,
) -> tuple[np.ndarray, WCS]:
    """Load one source image/WCS exactly once for ordered composition."""
    source_wcs = create_cell_wcs(placement.source_skycell, {"dataframe": current_df})
    if band_cache is not None and placement.source_skycell in band_cache:
        data = np.asarray(band_cache[placement.source_skycell]["combined_image"]).copy()
    else:
        # This mirrors the existing producer fallback exactly.  Failure is
        # intentionally fatal to the row: silently omitting a required source
        # produces a valid-looking but flux-deficient template.
        from syndiff_pipeline.template_creation.processing.ps1_process import (
            _load_skycell_raw_bands,
            project_gaia_to_skycell,
        )

        bands, masks, weights, headers, headers_weight = _load_skycell_raw_bands(
            placement.source_skycell, placement.source_projection, ingest_config
        )
        if not bands:
            raise RuntimeError(f"no source data for required padding cell {placement.source_skycell}")
        data, mask, uncert = process_skycell_bands(bands, masks, weights, headers, headers_weight)
        gaia_catalog_pixels = None
        if remove_saturated_stars and gaia_catalog is not None:
            gaia_catalog_pixels = project_gaia_to_skycell(gaia_catalog, source_wcs, data.shape)
        data, _ = remove_background(
            data, uncert, mask=mask, remove_saturated_stars=remove_saturated_stars,
            gaia_catalog_pixels=gaia_catalog_pixels,
            bright_star_mag_threshold=bright_star_mag_threshold,
        )
    return exclude_edge_pixels(data, EDGE_EXCLUSION), source_wcs


def prepare_ordered_padding_operations(
    *,
    placements: list[PaddingPlacement],
    target_array: np.ndarray,
    master_wcs: WCS,
    config,
    band_cache: dict | None,
    ingest_config: dict,
    remove_saturated_stars: bool,
    current_df: pd.DataFrame,
    gaia_catalog: pd.DataFrame | None = None,
    bright_star_mag_threshold: float = 13.0,
) -> list[tuple[int, np.ndarray, tuple[int, int, int, int], np.ndarray, np.ndarray]]:
    """Reproject ordered placements without mutating the target array.

    Preparation can later be parallelized safely.  Mutation is deliberately
    deferred to :func:`compose_ordered_reprojected_patches`, where priority is
    explicit and independent of worker scheduling.
    """
    loaded_sources: dict[str, tuple[np.ndarray, WCS]] = {}
    operations = []
    for placement in placements:
        if placement.source_skycell not in loaded_sources:
            loaded_sources[placement.source_skycell] = _load_padding_source_once(
                placement,
                band_cache=band_cache,
                ingest_config=ingest_config,
                remove_saturated_stars=remove_saturated_stars,
                current_df=current_df,
                gaia_catalog=gaia_catalog,
                bright_star_mag_threshold=bright_star_mag_threshold,
            )
        data, source_wcs = loaded_sources[placement.source_skycell]
        target_wcs, target_shape, (y_center, x_center) = create_padding_wcs(
            master_wcs, config, placement.location, placement.recipient_index
        )
        reprojected, footprint = reproject_interp(
            (data, source_wcs), target_wcs, shape_out=target_shape, order="bilinear"
        )
        height, width = target_shape
        y0 = int(y_center - height / 2)
        x0 = int(x_center - width / 2)
        y1, x1 = y0 + height, x0 + width
        if y0 < 0 or x0 < 0 or y1 > target_array.shape[0] or x1 > target_array.shape[1]:
            raise RuntimeError(
                f"required padding {placement.source_skycell} -> {placement.recipient_skycell} "
                f"({placement.location}) lies outside the producer master array"
            )
        operations.append((placement.priority, target_array, (y0, y1, x0, x1), reprojected, footprint))
    return operations


def identify_all_padding_sources(
    projections: List[str],
    df: pd.DataFrame,
    csv_path: str,
) -> tuple:
    """
    Scan all projections and rows to build:
    - source_cells: dict mapping skycell_name -> source_projection for every
      unique cross-projection padding source needed.
    - band_cache_uses: dict mapping skycell_name -> number of row-step uses
      (one per apply_cross_projection_padding call that needs this cell).
    - row_padding_map: dict mapping (projection_str, current_row_id) -> set of
      skycell_names consumed in that step (union of current + next row
      padding, deduplicated the same way ordered-placement composition
      loads each source skycell only once).

    Uses a pre-loaded CSV DataFrame to avoid repeated disk reads.
    """
    csv_data = load_csv_data(csv_path)

    source_cells: Dict[str, str] = {}
    band_cache_uses: Dict[str, int] = {}
    row_padding_map: Dict[tuple, set] = {}

    for projection in projections:
        proj_df = df[df["projection"].astype(str) == str(projection)]
        if proj_df.empty:
            continue

        # Build lightweight rows dict: row_id -> [(cell_name, x_coord), ...]
        rows: Dict[int, List[tuple]] = {}
        for _, row in proj_df.iterrows():
            row_id = int(row["y"])
            cell_name = str(row["NAME"])
            x_coord = int(row["x"]) if "x" in row.index else 0
            if row_id not in rows:
                rows[row_id] = []
            rows[row_id].append((cell_name, x_coord))

        all_row_ids = sorted(rows.keys())
        meta = {"projection": str(projection), "rows": rows, "dataframe": proj_df}

        for i, current_row_id in enumerate(all_row_ids):
            next_row_id = all_row_ids[i + 1] if i + 1 < len(all_row_ids) else None

            current_reqs = _parse_row_padding_requirements_df(meta, csv_data, current_row_id, all_row_ids)
            next_reqs: Dict[str, SkycellPaddingInfo] = {}
            if next_row_id is not None:
                next_reqs = _parse_row_padding_requirements_df(meta, csv_data, next_row_id, all_row_ids)

            # Union of cells used in this step (dedup, same as ordered-placement composition)
            step_cells: set = set(current_reqs.keys()) | set(next_reqs.keys())
            row_padding_map[(str(projection), current_row_id)] = step_cells

            for skycell_name in step_cells:
                info = current_reqs.get(skycell_name) or next_reqs.get(skycell_name)
                source_cells[skycell_name] = info.projection
                band_cache_uses[skycell_name] = band_cache_uses.get(skycell_name, 0) + 1

    return source_cells, band_cache_uses, row_padding_map


def parse_row_padding_requirements(metadata: dict, csv_path: str, row_id: int, all_row_ids: List[int]) -> Dict[str, SkycellPaddingInfo]:
    """
    Parse the CSV to find all cross-projection padding requirements for a specific row.
    Returns a dict mapping padding_skycell_name -> SkycellPaddingInfo.
    Delegates to _parse_row_padding_requirements_df after loading the CSV.
    """
    df = load_csv_data(csv_path)
    return _parse_row_padding_requirements_df(metadata, df, row_id, all_row_ids)


def apply_cross_projection_padding(state, config, metadata: dict, current_row_id: int, next_row_id: Optional[int], ingest_config: dict, csv_path: str, band_cache: dict = None, remove_saturated_stars: bool = True, gaia_catalog=None, bright_star_mag_threshold: float = 13.0):
    """
    Main entry point for applying cross-projection padding.
    Parallelized version. Accepts optional band_cache to skip zarr load + band
    processing for source cells already pre-computed by the pipeline.
    """
    # 1. Gather Requirements
    try:
        current_df = load_csv_data(csv_path)
    except Exception as e:
        logger.warning(f"Failed to load CSV {csv_path}: {e}")
        return

    current_projection = projection_identity(metadata["projection"])
    proj_df = current_df[current_df["projection"].map(projection_identity) == current_projection]
    all_row_ids = sorted(proj_df["y"].unique())

    current_placements = ordered_cross_projection_placements(
        metadata, current_df, current_row_id, all_row_ids
    )
    next_placements: list[PaddingPlacement] = []
    if next_row_id is not None:
        next_placements = ordered_cross_projection_placements(
            metadata, current_df, next_row_id, all_row_ids
        )

    if not current_placements and not next_placements:
        return

    logger.info(
        "[CrossPadding] Preparing %d ordered current and %d ordered next placements.",
        len(current_placements), len(next_placements),
    )

    # Rebase next-row priorities after the current row.  They target a
    # different array today, but this makes the order total and serialized in
    # diagnostics/provenance rather than accidental.
    next_placements = [
        PaddingPlacement(
            **{**placement.__dict__, "priority": placement.priority + len(current_placements)}
        )
        for placement in next_placements
    ]

    master_wcs = create_master_array_wcs(metadata, config, current_row_id)
    master_wcs_next = None
    if next_row_id is not None:
        master_wcs_next = create_master_array_wcs(metadata, config, next_row_id)
    operations = prepare_ordered_padding_operations(
        placements=current_placements,
        target_array=state.current_array,
        master_wcs=master_wcs,
        config=config,
        band_cache=band_cache,
        ingest_config=ingest_config,
        remove_saturated_stars=remove_saturated_stars,
        current_df=current_df,
        gaia_catalog=gaia_catalog,
        bright_star_mag_threshold=bright_star_mag_threshold,
    )
    if next_placements:
        if master_wcs_next is None:
            raise RuntimeError("next-row padding placements exist without a next-row WCS")
        operations.extend(prepare_ordered_padding_operations(
            placements=next_placements,
            target_array=state.next_array,
            master_wcs=master_wcs_next,
            config=config,
            band_cache=band_cache,
            ingest_config=ingest_config,
            remove_saturated_stars=remove_saturated_stars,
            current_df=current_df,
            gaia_catalog=gaia_catalog,
            bright_star_mag_threshold=bright_star_mag_threshold,
        ))
    compose_ordered_reprojected_patches(operations)
    logger.info("[CrossPadding] Applied %d ordered padding placements.", len(operations))
