"""Shared-mask package: empirical / TESSreduce bits, TNS, asteroids, MaskCatalog."""

from syndiff_pipeline.difference_imaging.masking.bits import (
    ASTEROID,
    BRIGHT_CAT,
    EDGE,
    EPSF_IGNORE_BITS,
    FAINT_CAT,
    HOTPANTS_IGNORE_BITS,
    PS1,
    SAT_CROSS,
    STRAP,
    STRAP_SOURCE_BITS,
    TNS,
    epsf_reject_mask,
    full_mask_bool,
    hotpants_mask_bool,
    strap_column_mask,
    strap_source_mask,
)
from syndiff_pipeline.difference_imaging.masking.catalog import MaskCatalog
from syndiff_pipeline.difference_imaging.masking.settings import (
    DEFAULT_TNS_PUBLIC_ZIP_URL,
    DEFAULT_TESS_ORBIT_TIMES_URL,
    MaskSettings,
    load_mask_settings,
    resolve_mask_settings,
)
from syndiff_pipeline.difference_imaging.masking.shared import Cat_mask, build_static_mask, make_shared_mask
from syndiff_pipeline.difference_imaging.masking.faint_star_squares import faint_star_squares
from syndiff_pipeline.difference_imaging.masking.ffi_mask import (
    btjd_for_ffi_id,
    load_catalog_for_event,
    load_catalog_for_scc_lane,
    load_ffi_times_table_for_lane,
    mask_bit_summary,
    mask_array_for_ffi_id,
    normalize_ffi_product_id,
    select_asteroid_active_ffi_ids,
    select_begin_mid_end_ffi_ids,
    write_mask_fits_for_ffi,
    write_sector_sample_mask_fits,
)
__all__ = [
    "ASTEROID",
    "BRIGHT_CAT",
    "EDGE",
    "EPSF_IGNORE_BITS",
    "FAINT_CAT",
    "HOTPANTS_IGNORE_BITS",
    "PS1",
    "SAT_CROSS",
    "STRAP",
    "STRAP_SOURCE_BITS",
    "TNS",
    "DEFAULT_TNS_PUBLIC_ZIP_URL",
    "DEFAULT_TESS_ORBIT_TIMES_URL",
    "Cat_mask",
    "MaskCatalog",
    "MaskSettings",
    "btjd_for_ffi_id",
    "build_static_mask",
    "epsf_reject_mask",
    "faint_star_squares",
    "full_mask_bool",
    "hotpants_mask_bool",
    "load_catalog_for_event",
    "load_catalog_for_scc_lane",
    "load_ffi_times_table_for_lane",
    "mask_bit_summary",
    "load_mask_settings",
    "make_shared_mask",
    "mask_array_for_ffi_id",
    "normalize_ffi_product_id",
    "resolve_mask_settings",
    "select_asteroid_active_ffi_ids",
    "select_begin_mid_end_ffi_ids",
    "strap_column_mask",
    "strap_source_mask",
    "write_mask_fits_for_ffi",
    "write_sector_sample_mask_fits",
]